export interface PhoneDetails {
  id: string,
	namespaceId: string,
	name: string,
	capacityAvailable: string[],
	capacity: string,
	priceRegular: 960,
	priceDiscount: 900,
	colorsAvailable: string[],
	color: string,
	images: string[],
	description: { title: string, text: string[] }[],
	screen: string,
	resolution: string,
	processor: string,
	ram: string,
	camera: string,
	zoom: string,
	cell: string[]
}
